#!/bin/sh /etc/rc.common

# Location: `/etc/init.d/dtuninit`.
# To enable: `/etc/init.d/dtuninit enable`.
# To start without rebooting: `/etc/init.d/dtuninit start`.

START=90
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/dtuninit
    procd_set_param pidfile /var/run/dtuninit.pid
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
